import fs from 'node:fs';
import { createHash } from 'node:crypto';
const data = JSON.parse(fs.readFileSync(new URL('./content.json',import.meta.url),'utf8'));
const root = new URL('./dist/',import.meta.url);
const version = name => createHash('sha256').update(fs.readFileSync(new URL(name,root))).digest('hex').slice(0,10);
const esc = value => String(value).replaceAll('&','&amp;').replaceAll('"','&quot;').replaceAll('<','&lt;').replaceAll('>','&gt;');
const names = {'data-logger':'MCU Data Logger','photoacoustic':'STM32H7 Photoacoustics','power-interfaces':'PPS / PV Interfaces','networked-nodes':'Four ESP32s + W5500'};
const iconPaths = {
 'data-logger':'<rect x="18" y="18" width="28" height="28" rx="4"/><rect x="25" y="25" width="14" height="14" rx="1"/><path d="M24 10v8m8-8v8m8-8v8M24 46v8m8-8v8m8-8v8M10 24h8m-8 8h8m-8 8h8m28-16h8m-8 8h8m-8 8h8"/>',
 'photoacoustic':'<path d="M8 33h10l5-17 9 32 8-25 6 10h10"/><path d="M12 10h10M12 10v10m40 34H42m10 0V44"/>',
 'power-interfaces':'<path d="m35 8-18 27h14l-2 21 18-28H33z"/><path d="M10 18v10m-5-5h10m35 23h9"/>',
 'networked-nodes':'<rect x="24" y="24" width="16" height="16" rx="3"/><circle cx="10" cy="10" r="5"/><circle cx="54" cy="10" r="5"/><circle cx="10" cy="54" r="5"/><circle cx="54" cy="54" r="5"/><path d="m14 14 10 10m16 0 10-10M14 50l10-10m16 0 10 10"/>'
};
const icon=p=>`<svg viewBox="0 0 64 64" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${iconPaths[p.id]}</svg>`;
const header=(prefix='')=>`<a class="skip" href="#main">Skip to content</a><header><a class="wordmark" href="${prefix}index.html" aria-label="Amlesh Sahoo home">AS<span> / </span>AMLESH SAHOO</a><nav aria-label="Main navigation"><a href="${prefix}index.html#work">Projects</a><a href="${prefix}about.html">About</a><a href="${prefix}assets/Amlesh-Sahoo-Resume.pdf" target="_blank" rel="noopener noreferrer">Resume ↗</a><a href="${prefix}index.html#contact">Contact</a></nav></header>`;
const footer=(prefix='')=>`<footer><span>© 2026 Amlesh Sahoo</span><button class="motion-toggle" type="button" aria-pressed="false" hidden>Pause animation</button><a href="${prefix}index.html#work">All projects</a><a href="https://github.com/buffer-cloud" target="_blank" rel="noopener noreferrer">GitHub ↗</a></footer>`;
const shell=(title,body,prefix='',path='')=>`<!doctype html>\n<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="theme-color" content="#f5f3ec"><meta name="description" content="Amlesh Sahoo — embedded systems, PCB design and data acquisition. Explore original engineering projects, code and research."><link rel="canonical" href="https://buffer-cloud.github.io/${path}"><title>${esc(title)} — Amlesh Sahoo</title><link rel="stylesheet" href="${prefix}style.css?v=${version('style.css')}"></head><body>${header(prefix)}<main id="main">${body}</main>${footer(prefix)}<script src="${prefix}motion.js?v=${version('motion.js')}" defer></script></body></html>`;
const gallery=data.projects.map(p=>`<a class="project-tile tile-${p.id}" href="projects/${p.id}.html" target="_blank" rel="noopener noreferrer"><div class="tile-top"><span class="eyebrow">${p.number} / ${esc(p.tags[0])}</span><span class="tile-arrow" aria-hidden="true">↗</span></div><div class="project-icon">${icon(p)}</div><h3>${names[p.id]}</h3><p>${esc(p.intro)}</p><span class="tile-link">Open project <span class="sr-only">in a new tab</span></span></a>`).join('');
const home=`<section class="gallery-hero"><div class="hero-circuit" aria-hidden="true"><svg viewBox="0 0 480 480" fill="none"><g class="circuit-orbit"><circle cx="240" cy="240" r="195"/><circle cx="240" cy="240" r="165" stroke-dasharray="2 14"/><path d="M240 45v45m195 150h-45M240 435v-45M45 240h45"/><circle cx="240" cy="45" r="7" class="signal-dot"/><circle cx="435" cy="240" r="7" class="signal-dot"/></g><g class="circuit-traces"><path d="M0 160h95l50 50h45M480 320h-95l-50-50h-45M160 0v95l50 50v45M320 480v-95l-50-50v-45M0 320h95l50-50h45M480 160h-95l-50 50h-45"/></g><rect x="184" y="184" width="112" height="112" rx="18" class="chip-outline"/><rect x="207" y="207" width="66" height="66" rx="8" class="chip-core"/><path d="M218 170v14m22-14v14m22-14v14M218 296v14m22-14v14m22-14v14M170 218h14m-14 22h14m-14 22h14M296 218h14m-14 22h14m-14 22h14"/><path class="chip-wave" d="M215 241h9l7-16 13 31 8-15h13"/></svg><span class="circuit-label">HARDWARE ↔ FIRMWARE ↔ INTERFACE</span></div><div class="eyebrow">ELECTRICAL ENGINEERING / EMBEDDED SYSTEMS</div><h1>From circuit.<br>To <em>system.</em></h1><div class="hero-bottom"><p>I’m Amlesh Sahoo. I build at the intersection of electronics, firmware, and data acquisition.</p><a class="text-link" href="#work">Explore my projects <span>↓</span></a></div></section><section id="work" class="gallery-section"><div class="section-head"><h2>Selected projects</h2><span class="eyebrow">OPEN A PROJECT TO EXPLORE</span></div><div class="project-grid">${gallery}</div></section><section class="home-about"><span class="eyebrow">A LITTLE ABOUT ME</span><h2>Curious about the whole system.</h2><p>Electrical Engineering student in the BITS Pilani–Iowa State University dual-degree program. Exploring how hardware, firmware, and interfaces work together.</p><a class="text-link" href="about.html">Experience & background <span>↗</span></a></section><section id="contact" class="section contact"><span class="eyebrow">LET’S CONNECT</span><h2>Build something<br>that <em>works.</em></h2><div id="contact-links"><a href="mailto:amlesh08@iastate.edu">amlesh08@iastate.edu ↗</a><a href="https://github.com/buffer-cloud" target="_blank" rel="noopener noreferrer">GitHub ↗</a><a href="https://www.linkedin.com/in/amlesh-swarup-sahoo-aab98a362" target="_blank" rel="noopener noreferrer">LinkedIn ↗</a></div></section>`;
fs.writeFileSync(new URL('index.html',root),shell('Engineering Portfolio',home));
const diagram=`<div class="architecture" aria-label="Proposed acquisition path"><span class="eyebrow">PROPOSED ACQUISITION PATH</span><div class="pipeline"><div><small>01 / TIMING</small><strong>Timer trigger</strong></div><span>→</span><div><small>02 / CAPTURE</small><strong>STM32H7 ADC</strong></div><span>→</span><div><small>03 / BUFFER</small><strong>DMA → RAM</strong></div></div><div class="planned-path"><span>PLANNED TRANSFER</span><strong>ESP32 gateway</strong><span>→</span><strong>Host interface</strong></div></div>`;
fs.mkdirSync(new URL('projects/',root),{recursive:true});
for(const [index,p] of data.projects.entries()){
 const visual=p.diagram?`<figure class="detail-visual diagram-visual">${diagram}<figcaption>${esc(p.caption)}</figcaption></figure>`:`<figure class="detail-visual visual-${p.id}${p.secondary?' paired-detail':''}"><div class="detail-image-grid"><img src="../${p.image}" alt="${esc(p.caption)}" decoding="async">${p.secondary?`<img src="../${p.secondary}" alt="${esc(p.id==='networked-nodes'?'Lower two panels of the four-ESP32 W5500 dashboard from the IIT Hyderabad report':'PPS Monitor interface from the IIT Hyderabad report')}" decoding="async">`:''}</div><figcaption>${esc(p.caption)}</figcaption></figure>`;
 const snapshots=(p.codeSnapshots||[]).map(s=>`<figure class="code-snapshot"><div class="code-window-bar"><span>${esc(s.file)}</span><span>${esc(s.locationLabel || s.language || 'SOURCE')}</span></div>${s.image?`<a href="../${s.image}" target="_blank" rel="noopener noreferrer" aria-label="Open full-size ${esc(s.file)} code snapshot"><img src="../${s.image}" alt="${esc(s.caption)}" loading="lazy"></a>`:`<pre><code>${esc(s.code)}</code></pre>`}<figcaption>${esc(s.caption)}${s.source?` <a href="${esc(s.source)}" target="_blank" rel="noopener noreferrer">View original source ↗</a>`:''}</figcaption>${s.image&&s.code?`<details class="code-text"><summary>Read accessible code text</summary><pre><code>${esc(s.code)}</code></pre></details>`:''}</figure>`).join('');
 const codeSection=`<section class="detail-code"><div class="section-head"><h2>Inside the ${p.id==='data-logger'?'design':'code'}</h2><span class="eyebrow">${snapshots?'SOURCE SNAPSHOTS':'DEVELOPMENT RECORD'}</span></div>${snapshots||`<p class="evidence-note">${p.id==='photoacoustic'?'This research is still in development. No verified firmware source is available to publish here yet; the architecture above shows the proposed system.':p.id==='networked-nodes'?'The original internship report captures the code and serial output below. A standalone source repository has not been published.':'Source snapshots are being prepared from the project files.'}</p>${p.id==='networked-nodes'?`<figure class="detail-gallery"><a href="../assets/priority-messages.png" target="_blank" rel="noopener noreferrer"><img src="../assets/priority-messages.png" alt="Original report screenshot showing ESP32 code and serial messages" loading="lazy"></a><figcaption>Original code and serial output screenshot from the internship report. Open to view full size.</figcaption></figure>`:''}`}</section>`;
 const next=data.projects[(index+1)%data.projects.length];
 const body=`<div class="project-page"><a class="back-link" href="../index.html#work">← All projects</a><section class="project-page-heading"><div class="detail-title-row"><div class="detail-icon">${icon(p)}</div><span class="eyebrow">PROJECT ${p.number} / ${esc(p.status)}</span></div><h1>${names[p.id]}</h1><p class="project-lede">${esc(p.intro)}</p><div class="tags">${p.tags.map(t=>`<span>${esc(t)}</span>`).join('')}</div></section>${visual}<section class="case-body case-page-body">${p.sections.map(s=>`<div><h2>${esc(s.title)}</h2><p>${esc(s.text)}</p></div>`).join('')}</section>${p.detailImage?`<section class="project-gallery"><h2>${p.id==='data-logger'?'Fabrication view':'A closer look'}</h2><figure class="detail-gallery"><a href="../${p.detailImage}" target="_blank" rel="noopener noreferrer"><img src="../${p.detailImage}" alt="${esc(p.detailCaption)}" loading="lazy"></a><figcaption>${esc(p.detailCaption)} Open image for full resolution.</figcaption></figure></section>`:''}${codeSection}<div class="project-resources">${p.repo?`<a class="text-link" href="${p.repo}" target="_blank" rel="noopener noreferrer">Project repository <span>↗</span></a>`:''}${p.download?`<a class="text-link" href="../${p.download}">Download fabrication files <span>↓</span></a>`:''}<a class="text-link" href="../index.html#work">All projects <span>←</span></a></div><a class="next-project" href="${next.id}.html"><span class="eyebrow">NEXT PROJECT</span><strong>${names[next.id]}</strong><span>→</span></a></div>`;
 fs.writeFileSync(new URL(`projects/${p.id}.html`,root),shell(names[p.id],body,'../',`projects/${p.id}.html`));
}
const about=`<div class="about-page"><a class="back-link" href="index.html">← Home</a><div class="eyebrow">BACKGROUND / EXPERIENCE</div><h1>Curious about the<br><em>whole system.</em></h1><p class="project-lede">I’m Amlesh Sahoo, an Electrical Engineering student in the BITS Pilani–Iowa State University dual-degree program, based in Ames, Iowa.</p><p class="about-description">My work moves between circuit design, embedded programming, and the interfaces that make measurements useful. I’m interested in how the whole path fits together—from a signal on a board to data someone can understand.</p><section class="about-experience"><h2>Experience</h2><div class="experience-row"><span class="date">2026 — PRESENT</span><div><h3>Iowa State University</h3><p>Undergraduate Research Intern</p></div><p>Embedded acquisition for pulsed-LED photoacoustic tomography.<br>Prof. Manojit Pramanik</p></div><div class="experience-row"><span class="date">JUN — JUL 2025</span><div><h3>IIT Hyderabad</h3><p>Summer Research Intern</p></div><p>ESP32 systems, power interfaces, and connected visualization.<br>Prof. Rupesh Wandhere</p></div></section><section class="about-experience"><h2>Technical practice</h2>${[['Hardware & measurement','KiCad · LTspice · PCB layout · Bench prototyping'],['Embedded development','C / C++ · STM32H7 · ESP32 · ADC / DMA / Timers · SPI / I²C'],['Connected systems','W5500 Ethernet · WebSockets · Wi-Fi · BLE · Bluetooth Classic'],['Interfaces & visualization','Flutter / Dart · TFT displays · Touch interfaces · CSV export']].map(([h,p])=>`<div class="stack-row"><h3>${h}</h3><p>${p}</p></div>`).join('')}</section><section class="education"><h2>Education</h2><p>BITS Pilani–Iowa State University · 2024–2028</p><p>B.E. Electronics and Communication Engineering + B.S. Electrical Engineering</p></section><a class="text-link" href="assets/Amlesh-Sahoo-Resume.pdf" target="_blank" rel="noopener noreferrer">Read my resume <span>↗</span></a></div>`;
fs.writeFileSync(new URL('about.html',root),shell('About & Experience',about,'','about.html'));
console.log('Built homepage, about page, and four dedicated project pages.');
